package com.cafe24.crm.domain.neo4j;

import lombok.*;
import org.springframework.data.neo4j.core.schema.GeneratedValue;
import org.springframework.data.neo4j.core.schema.Id;
import org.springframework.data.neo4j.core.schema.Node;
import org.springframework.data.neo4j.core.schema.Property;
import org.springframework.data.neo4j.core.schema.Relationship;
import org.springframework.data.neo4j.core.support.UUIDStringGenerator;

import java.time.LocalDate;
import java.time.LocalDateTime;
import java.util.HashSet;
import java.util.Set;

/**
 * Neo4j Node Entity for CRM Customer
 *
 * Represents a customer in the CRM graph database with RFM analysis scores,
 * customer lifetime value (CLV), and segment classification.
 */
@Node("CRM_Customer")
@Getter
@Setter
@NoArgsConstructor
@AllArgsConstructor
@Builder
@ToString(exclude = {"orders", "viewedProducts", "purchasedProducts"})
@EqualsAndHashCode(of = "customerId")
public class CrmCustomerNode {

    @Id
    @GeneratedValue(UUIDStringGenerator.class)
    private String id;

    /**
     * Unique customer identifier from source system
     */
    @Property("customer_id")
    private String customerId;

    /**
     * Customer display name
     */
    @Property("name")
    private String name;

    /**
     * Customer email address
     */
    @Property("email")
    private String email;

    /**
     * Phone number
     */
    @Property("phone")
    private String phone;

    /**
     * Customer segment classification (VIP, Premium, Regular, New, At-Risk, Churned)
     */
    @Property("segment")
    private String segment;

    /**
     * Composite RFM score (1-5 scale for each dimension)
     */
    @Property("rfm_score")
    private String rfmScore;

    /**
     * Recency score (1-5): How recently did the customer purchase?
     */
    @Property("recency")
    private Integer recency;

    /**
     * Frequency score (1-5): How often do they purchase?
     */
    @Property("frequency")
    private Integer frequency;

    /**
     * Monetary score (1-5): How much do they spend?
     */
    @Property("monetary")
    private Integer monetary;

    /**
     * Total number of orders placed
     */
    @Property("total_orders")
    private Integer totalOrders;

    /**
     * Total revenue generated by this customer
     */
    @Property("total_revenue")
    private Double totalRevenue;

    /**
     * Customer Lifetime Value prediction
     */
    @Property("clv")
    private Double clv;

    /**
     * Average order value
     */
    @Property("avg_order_value")
    private Double avgOrderValue;

    /**
     * Date of first order
     */
    @Property("first_order_date")
    private LocalDate firstOrderDate;

    /**
     * Date of most recent order
     */
    @Property("last_order_date")
    private LocalDate lastOrderDate;

    /**
     * Days since last purchase
     */
    @Property("days_since_last_purchase")
    private Integer daysSinceLastPurchase;

    /**
     * Customer registration date
     */
    @Property("created_at")
    private LocalDateTime createdAt;

    /**
     * Last profile update timestamp
     */
    @Property("updated_at")
    private LocalDateTime updatedAt;

    /**
     * Customer status (active, inactive, churned)
     */
    @Property("status")
    private String status;

    /**
     * Preferred product category
     */
    @Property("preferred_category")
    private String preferredCategory;

    /**
     * Churn probability (0.0 - 1.0)
     */
    @Property("churn_probability")
    private Double churnProbability;

    /**
     * Customer tier level
     */
    @Property("tier")
    private String tier;

    // Relationships

    /**
     * Orders placed by this customer
     */
    @Relationship(type = "PLACED_ORDER", direction = Relationship.Direction.OUTGOING)
    @Builder.Default
    private Set<CrmOrderNode> orders = new HashSet<>();

    /**
     * Products this customer has viewed
     */
    @Relationship(type = "VIEWED", direction = Relationship.Direction.OUTGOING)
    @Builder.Default
    private Set<CrmProductNode> viewedProducts = new HashSet<>();

    /**
     * Products this customer has purchased
     */
    @Relationship(type = "PURCHASED", direction = Relationship.Direction.OUTGOING)
    @Builder.Default
    private Set<CrmProductNode> purchasedProducts = new HashSet<>();

    /**
     * Calculate composite RFM segment string
     */
    public String getRfmSegment() {
        if (recency == null || frequency == null || monetary == null) {
            return "Unknown";
        }
        int r = recency != null ? recency : 0;
        int f = frequency != null ? frequency : 0;
        int m = monetary != null ? monetary : 0;

        if (r >= 4 && f >= 4 && m >= 4) return "Champions";
        if (r >= 3 && f >= 3 && m >= 3) return "Loyal";
        if (r >= 4 && f <= 2) return "New Customers";
        if (r <= 2 && f >= 3 && m >= 3) return "At Risk";
        if (r <= 2 && f <= 2) return "Hibernating";
        return "Regular";
    }
}
